---
resources:
  - ../base
patches:
  # Customize for external ceph cluster.
  - target:
      kind: PersistentVolumeClaim
      name: funnybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-external-storagecluster-ceph-rbd
