---
resources:
  - ../base
patches:
  # Customize for internal cephfs storage.
  - target:
      kind: PersistentVolumeClaim
      name: funnybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-cephfs
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
